import { ClassItem } from "@/types";

export const classes: ClassItem[] = [
  {
    id: 1,
    name: "CrossFit",
    description:
      "Entrenamiento de boxeo para mejorar la resistencia, fuerza y técnica",
    image: "/classes/image.jpg",
    tags: ["Clase grupal"],
    category: "crossfit",
    specialTags: ["Clase de prueba"],
    date: "2026-04-21T18:00:00Z",
    duration: 45,
    commune: "Santiago",
    price: 5000,
    sportCentar: "Rocket Box",
    availableSpots: 5,
  },
  {
    id: 2,
    name: "Yoga",
    description:
      "Práctica de posturas y respiración para mejorar la flexibilidad y el bienestar mental",
    image: "/classes/image-3.jpg",
    tags: ["Clase grupal"],
    category: "yoga",
    date: "2026-04-21T18:00:00Z",
    duration: 60,
    commune: "Santiago",
    sportCentar: "Monster",
    price: 5000,
    availableSpots: 5,
  },
  {
    id: 3,
    name: "Entrenamiento Funcional",
    description:
      "Ejercicios que imitan movimientos cotidianos para mejorar la fuerza y la movilidad",
    image: "/classes/image-2.jpg",
    tags: ["Clase grupal"],
    category: "Funcional",
    date: "2026-04-21T18:00:00Z",
    duration: 45,
    commune: "Santiago",
    sportCentar: "Rocket Box",
    price: 5000,
    availableSpots: 5,
  },
  {
    id: 4,
    name: "HYBRID",
    description:
      "Combinación de diferentes estilos de entrenamiento para una experiencia completa",
    image: "/classes/image-1.jpg",
    tags: ["Clase grupal"],
    category: "Funcional",
    date: "2026-04-21T18:00:00Z",
    duration: 45,
    commune: "Santiago",
    sportCentar: "Puro Pony",
    price: 5000,
    availableSpots: 5,
  },
  {
    id: 5,
    name: "Pilates",
    description:
      "Ejercicios de control del cuerpo para mejorar la postura y la fuerza",
    image: "/classes/image-5.jpg",
    tags: ["Clase grupal"],
    category: "Pilates",
    date: "2026-04-21T18:00:00Z",
    duration: 45,
    commune: "Santiago",
    sportCentar: "Alma studio",
    price: 5000,
    availableSpots: 5,
  },
  {
    id: 6,
    name: "Danza Árabe",
    description:
      "Clases de danza árabe para mejorar la coordinación y la expresión corporal",
    image: "/classes/image-4.jpg",
    tags: ["Clase grupal"],
    category: "Danza",
    date: "2026-04-21T18:00:00Z",
    duration: 45,
    commune: "Santiago",
    sportCentar: "Habibi",
    price: 5000,
    availableSpots: 5,
  },
  {
    id: 7,
    name: "Crosstraining",
    description:
      "Entrenamiento que combina ejercicios de fuerza, cardio y flexibilidad",
    image: "/classes/image-1.jpg",
    tags: ["Clase grupal"],
    category: "Funcional",
    date: "2026-04-21T18:00:00Z",
    duration: 45,
    commune: "Santiago",
    sportCentar: "Puro Pony",
    price: 5000,
    availableSpots: 5,
  },
  {
    id: 8,
    name: "Clase de salsa",
    description:
      "Clases de salsa para aprender los pasos básicos y mejorar la coordinación",
    image: "/classes/image-7.jpg",
    tags: ["Clase grupal"],
    category: "Danza",
    date: "2026-04-21T18:00:00Z",
    duration: 45,
    commune: "Santiago",
    sportCentar: "Academia de baile Sabor Latino",
    price: 5000,
    availableSpots: 5,
  },
];
