import { SportCenterItem } from "@/types";

export const sportCenters: SportCenterItem[] = [
  {
    id: "rocket-box",
    name: "Rocket Box",
    logo: "/sportcenters/sc-fake.png",
    bannerImage: "/classes/image.jpg",
    address: "Av. Alessandri 9964",
    commune: "Curicó",
    region: "Maule",
    email: "monsterfit@gmail.com",
    categories: ["Funcional", "Hybrid training", "Barbell", "Weightlifting"],
    socials: {
      website: "https://rocketbox.cl",
      instagram: "https://instagram.com/rocketbox",
      tiktok: "https://tiktok.com/@rocketbox",
    },
  },
  {
    id: "yoga-zen-studio",
    name: "Yoga Zen Studio",
    logo: "/sportcenters/sc-fake.png",
    bannerImage: "/classes/image-3.jpg",
    address: "Pasaje del Sol 45",
    commune: "Curicó",
    region: "Maule",
    email: "info@yogazenstudio.cl",
    categories: ["Yoga", "Pilates", "Meditación"],
    socials: {
      instagram: "https://instagram.com/yogazenstudio",
    },
  },
  {
    id: "pilates-studio",
    name: "Pilates Studio",
    logo: "/sportcenters/sc-fake.png",
    bannerImage: "/classes/image-5.jpg",
    address: "Av. San Martín 123",
    commune: "Viña del Mar",
    region: "Valparaíso",
    email: "contacto@pilatesstudio.cl",
    categories: ["Pilates", "Yoga"],
    socials: {
      website: "https://pilatesstudio.cl",
      instagram: "https://instagram.com/pilatesstudio",
    },
  },
  {
    id: "club-habibi",
    name: "Club Habibi",
    logo: "/sportcenters/sc-fake.png",
    bannerImage: "/classes/image-4.jpg",
    address: "Calle 2 Sur 1045",
    commune: "Talca",
    region: "Maule",
    email: "info@clubhabibi.cl",
    categories: ["Danza", "Árabe", "Zumba"],
    socials: {
      instagram: "https://instagram.com/clubhabibi",
      tiktok: "https://tiktok.com/@clubhabibi",
    },
  },
  {
    id: "monkeys-fitness-community",
    name: "Monkeys Fitness Community",
    logo: "/sportcenters/sc-fake.png",
    bannerImage: "/classes/image-1.jpg",
    address: "Av. Manso de Velasco 654",
    commune: "Curicó",
    region: "Maule",
    email: "hola@monkeysfitness.cl",
    categories: ["Funcional", "CrossFit", "Cardio"],
    socials: {
      website: "https://monkeysfitness.cl",
      instagram: "https://instagram.com/monkeysfitness",
    },
  },
  {
    id: "escuela-de-danza-la-pininola",
    name: "Escuela de danza La Piñinola",
    logo: "/sportcenters/sc-fake.png",
    bannerImage: "/classes/image-7.jpg",
    address: "Calle Chacabuco 321",
    commune: "Curicó",
    region: "Maule",
    email: "lapininola@danza.cl",
    categories: ["Danza", "Salsa", "Bachata"],
    socials: {
      instagram: "https://instagram.com/lapininola",
      tiktok: "https://tiktok.com/@lapininola",
    },
  },
];
